title: Surya Raman
email: hello@suryaraman.dev
description: Senior Engineering Leader • Backend Architect • Human
url: "https://suryaraman.dev"
lang: "en"
keywords: "Senior Engineering Leader, Backend Architect, Go Developer, Node.js, TypeScript, AWS, Kubernetes, Docker, PostgreSQL, MySQL, MongoDB, Elasticsearch, Linux, Git, Toronto, Canada"

# ALl my social media
social:
  twitter:
    url: https://twitter.com/ayrusme
  github:
    url: https://github.com/ayrusme
  linkedin:
    url: https://www.linkedin.com/in/suryaraman/
  stack-overflow:
    url: https://stackoverflow.com/users/3831618/thatrockbottomprogrammer
  topmate:
    url: https://topmate.io/surya_raman/
    fa-icon-family: fas
    fa-icon-class: fa-seedling

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Site Pages
collections:
  blogs:
    output: true
    permalink: /:collection/:path/

sass:
  sass_dir: _scss
  style: compressed

future: true