title: Surya Raman
email: hello@suryaraman.dev
description: Developer. Human. 
url: "https://suryaraman.dev"
lang: "en"

# ALl my social media
social:
  twitter: https://twitter.com/ayrusme
  github:  https://github.com/ayrusme
  linkedin: https://www.linkedin.com/in/suryaraman/
  stack-overflow: https://stackoverflow.com/users/3831618/ayrusme

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Site Pages
collections:
  blogs:
    output: true
    permalink: /:collection/:path

sass:
  sass_dir: _scss
  style: compressed
