title: Surya Raman
email: hello@suryaraman.dev
description: Developer. Human. 
url: "https://suryaraman.dev"
lang: "en"

# ALl my social media
social:
  twitter: https://twitter.com/ayrusme
  github:  https://github.com/ayrusme
  linkedin: https://www.linkedin.com/in/suryaraman/
  spotify: https://open.spotify.com/user/ayrusme?si=jTzwA7FEROiFlnZCBTOyTg
  stack-overflow: https://stackoverflow.com/users/3831618/thatrockbottomprogrammer

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Site Pages
collections:
  blogs:
    output: true
    permalink: /:collection/:path/

sass:
  sass_dir: _scss
  style: compressed
